### ISSUE TITLE
When updating ESP32 boards 3.0.1 it break the library - unqualified-id before ')' token StaticBlinker<TIMEOUT>(): timer(){};

### ISSUE THREAD

**Issue by iamsstef** [rtnate/arduino-BasicTimer#2]
Since updating to the latest ESP32 board v3.0.1 i get the follwing error when compiling.

\arduino\libraries\basictimer\src\basicblinker.h:188:32: error: expected unqualified-id before ')' token
  188 |         StaticBlinker<TIMEOUT>(): timer(){};

**Comment by rtnate** [comment]
Looks like the template argument is supplied to the constructor there, which is nonstandard C++ but for some reason doesn't bother my compilers.  Changing Line 188 should fix it :
```
//StaticBlinker<TIMEOUT>(): timer(){}; //WRONG
StaticBlinker(): timer(){}; //RIGHT
```

I'll try and get a fix committed ASAP.

**Comment by iamsstef** [comment]
Thanks that sorted it!
